Weather app
janis-jenny/Weather-App pull request #2
Opened 2021-05-23 18:10 UTC by janis-jenny

- [ ]  Install webpack plugins and loaders from a template
- [ ]  Create 3 Classes: ApiData, Render and Form
- [ ]  Use DOM to render the data of a city.

2021-05-24 04:04 UTC, rindrajosia requested changes
Invalid :red_circle: 
The project should have a descriptive README.md. The title of the project and the project description description don't correspond to your APP.
Please use this file as linter config : [.github/workflows/linters.yml](https://github.com/microverseinc/linters-config/blob/master/javascript/.github/workflows/linters.yml)

2021-05-25 09:23 UTC, umairarshadbutt requested changes
# Status: REQUIRED CHANGES :warning: :construction: 

Hi 
Such a remarkable project you made :+1: ! Awesome README :100: !
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed.

##

Kindly work on the suggested changes  👇.
- [ ] Remove commented code and console from JavaScript file.([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
- [x] Live link is not found in the readme file.
- [ ] Please add more instructions about the `.env` file in `How it works` README file section. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
- [ ] API response is giving the 401 status in networks and in dom it is showing 404 status

##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad (Code Reviewer)](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2021-05-25 09:23 UTC, umairarshadbutt commented on src/index.js
> +// console.log(process.env.DB_HOST);
remove commented code

2021-05-25 09:23 UTC, umairarshadbutt commented on src/components/background.js
> +  console.log(data.weather.toLowerCase());
Remove `console` statement

2021-05-25 09:23 UTC, umairarshadbutt commented on src/components/form.js
> +    console.log(value);
Remove `console` statements

2021-05-26 19:36 UTC, Temmarie approved these changes
## Status: Approved :heavy_check_mark:

### Hi @janis-jenny  ! :wave:

#### Thank you for making all of the required changes, your project is approved :clap: :clap: :clap: :tada:
 
#### You may merge, good luck with your next projects! :rocket:
#### Happy Coding! :+1:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

2021-05-26 19:36 UTC, Temmarie commented on src/components/api.js
> +export { BASE_URL, API_KEY };
- [ ] _[OPTIONAL]_ Inline comment:

With the ESLint inline comment, you're are indirectly changing the linter's rules by disabling these rules, let's fix the codebase instead.

If you are using VSCode, you can delete the inline comment and hover over the error(configure eslint checks locally). And you will see your options. Click on the more info button that will take you to a GitHub repo where it is explained why you are getting this error. I find this feature very educational. Please, try to learn and implement the necessary rules so you don't have to keep this disabling line on top of each file. I believe you can do this! 💪😇

2021-05-26 19:36 UTC, Temmarie commented on src/components/form.js
> +}
- [ ] _[OPTIONAL]_ Consider refactoring your code to fix the underlying eslint issues instead of disabling it.

2021-05-26 20:52 UTC, merged